forum/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.sitemaps.views import sitemap
from forumsite.sitemaps import PostSitemap


sitemaps = {
    'posts':PostSitemap
}
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('forumsite.urls',namespace='forum')),
    path('sitemap.xml',sitemap,{'sitemaps':sitemaps},name="django.contrib.sitemaps.views.sitemap")
]

forumsite/urls.py
from django.urls import path 
from forumsite import views #from . import views
from .feeds import LatestPostsFeed


app_name = 'forumsite'
urlpatterns = [
      path('',views.post_list,name='post_list'),
  path('tag/<slug:tag_slug>/',views.post_list,name='post_list_by_tag'),
  # path('',views.PostListView.as_view(),name='post_list'),
  path('<int:year>/<int:month>/<int:day>/<slug:post>/',views.post_detail, name='post_detail'),
  path('<int:post_id>/share',views.post_share,name='post_share'),
  path('<int:post_id>/comment/',views.post_comment,name='post_comment'),
  path('feed/',LatestPostsFeed(),name='post_feed'),
  path('search/',views.post_search,name='post_search'),
]

forumsite/models.py
from django.db import models
from taggit.managers import TaggableManager

# Create your models here.
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
#creating model managers instead of using the default "object" manager
class PublishedManager(models.Manager):
  def get_queryset(self):
    return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
  class Status(models.TextChoices):
    # DF = Value, Draft = Label, DRAFT= name
    DRAFT = 'DF','Draft'
    PUBLISHED = 'PB','Published'
    

 
  title = models.CharField(max_length=250)
  # image = models.ImageField(upload_to='src/images/')
  slug = models.SlugField(max_length=250, unique_for_date ='publish')
  author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
  body = models.TextField()
  publish = models.DateTimeField(default = timezone.now)
  created = models.DateTimeField(auto_now_add = True)
  updated = models.DateTimeField(auto_now = True)
  status = models.CharField(max_length=2,choices = Status.choices,default = Status.DRAFT)
  objects = models.Manager() #default manager
  published = PublishedManager()  #custom manager
  tags = TaggableManager()

  class Meta:
    ordering = ['-publish']
    indexes = [models.Index(fields=['-publish'],)]

  def __str__(self):
    return self.title 

  def get_absolute_url(self):
    return reverse('forum:post_detail',args=[self.publish.year,
                  self.publish.month,self.publish.day,self.slug])

class Comment(models.Model):
  post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
  name = models.CharField(max_length=100)
  email = models.EmailField()
  body = models.TextField()
  created = models.DateTimeField(auto_now_add=True)
  updated = models.DateTimeField(auto_now=True)
  active = models.BooleanField(default=True)
  
  class Meta:
    ordering=['created']
    indexes = [models.Index(fields=['created'])]
    
  def __str__(self):
    return f'Comment by {self.name} on {self.post}'

forumsite/forms.py
from django import forms 
from .models import Comment

class EmailPostForm(forms.Form):
  name = forms.CharField(max_length=300)
  email = forms.EmailField()
  to = forms.EmailField()
  comments = forms.CharField(required=False,widget=forms.Textarea)
  
class CommentForm(forms.ModelForm):
  class Meta:
    model = Comment
    fields = ['name','email','body']


class SearchForm(forms.Form):
  query = forms.CharField()

forumsite/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from .models import Post,Comment
from django.views.generic import ListView
from django.core.paginator import Paginator, EmptyPage,PageNotAnInteger
from .forms import EmailPostForm,CommentForm,SearchForm
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from taggit.models import Tag
from django.db.models import Count 
from django.contrib.postgres.search import SearchVector, SearchQuery,SearchRank


# Create your views here.


def post_list(request, tag_slug=None):
  post_list = Post.published.all()
  tag = None
  if tag_slug:
    tag = get_object_or_404(Tag,slug=tag_slug)
    post_list = post_list.filter(tags__in=[tag])
  paginator = Paginator(post_list,6) #3 posts per page
  page_number = request.GET.get('page',1)
  try:
    posts = paginator.page(page_number)
  except PageNotAnInteger:
    posts = paginator.page(1) #deliver first page is page is not an integer
  except EmptyPage:
    posts = paginator.page(paginator.num_pages) #always return last page if not page number is found
  return render(request,'forumsite/post/list.html',{'posts':posts,'tag':tag})


# class based view
# class PostListView(ListView):
#   queryset = Post.published.all()
#   context_object_name = 'posts'
#   paginate_by=3
#   template_name = 'blog/post/list.html'


def post_detail(request, year, month, day, post):
  post = get_object_or_404(Post,status =Post.Status.PUBLISHED,
                          slug=post,publish__year = year, publish__month=month,
                          publish__day=day)
  comments = post.comments.filter(active=True)
  form = CommentForm()
  post_tags_ids = post.tags.values_list('id', flat=True)
  similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
  similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]
  return render(request,'forumsite/post/detail.html',{'post':post,'comments':comments,'form':form,'similar_posts':similar_posts})
  
def post_share(request,post_id):
  post = get_object_or_404(Post,id=post_id,status=Post.Status.PUBLISHED)
  sent = False
  if request.method =='POST':
    form = EmailPostForm(request.POST)
    if form.is_valid():
      cd = form.cleaned_data
      post_url = request.build_absolute_uri(post.get_absolute_url())
      subject = f"{cd['name']} recommends you read {post.title}"
      message = f"Read {post.title} at {post_url} {cd['name']}\'s comments: {cd['comments']}"
      send_mail(subject,message,"matthewofomi2015@gmail.com",[cd['to']])
      sent = True
  else:
      form = EmailPostForm()
  return render(request,'forumsite/post/share.html',{'post':post,'form':form,'sent':sent})

@require_POST
def post_comment(request,post_id):
  post = get_object_or_404(Post,id=post_id,status=Post.Status.PUBLISHED)
  comment = None
  form = CommentForm(data=request.POST)
  if form.is_valid():
    comment = form.save(commit=False)
    comment.post = post
    comment.save()
  return render(request,'forumsite/post/comment.html',{'post':post,'form':form,'comment':comment})

def post_search(request):
  form = SearchForm()
  query = None
  results =[]
  if 'query' in request.GET:
    form = SearchForm(request.GET)
    if form.is_valid():
      query = form.cleaned_data['query']
      search_vector = SearchVector('title',weight='A') + SearchVector('body',weight='B')
      search_query = SearchQuery(query)
      results = Post.published.annotate(search=search_vector,rank=SearchRank(search_vector,search_query)).filter(rank__gte=0.3).order_by('-rank')
  return render(request,'forumsite/post/search.html',{'form':form,'query':query,'results':results})

forumsite/templates/forumsite/base.html
{% load forumsite_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %} {% endblock %}</title>
  {% comment %} <link rel="stylesheet" href="{% static 'css/blog.css' %}"> {% endcomment %}
  {% comment %} <script src="https://cdn.tailwindcss.com"></script> {% endcomment %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

  <div class="container">
    <div id="sidebar">
      <h2 class="">My Blog</h2>
      <p>This is my blog</p>
      <p>Total number of Posts: {% my_tag %}</p>
      <p>
        <a href="{% url 'forumsite:post_feed' %}">Subscribe to my RSS feed</a>
      </p>
      <h3 class="fs-4">Latest posts</h3>
      {% show_latest_posts 3 %}
      <h3 class="fs-4">Most commented posts</h3>
      {% most_commented_posts as commented_posts %}
      <ul>
        
        {% for post in commented_posts %}
          <li>
            <a href="{{post.get_absolute_url}}">{{post.title}}</a>
          </li>
        {% endfor %}
          
      </ul>
    </div>
  <div id="'content">
    {% block content %} 
    {% endblock content %} 

  </div>

 
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

forumsite/templates/forumsite/post/comment.html
{% extends "forumsite/base.html" %}
{% comment %} {% extends "forumsite/base.html" %}

{% block title %}Add a comment{% endblock title %}
{% block content %}

{% if comment %}
<h2>Your comment has been added</h2>
<p><a href="{{post.get_absolute_url}}">Back to the post</a></p>
  {% else %}
  {% include "forumsite/post/includes/comment_form.html" %}
{% endif %}
  

{% endblock content %}
 {% endcomment %}



{% block title %}Add a comment{% endblock title %}
{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      {% if comment %}
      <div class="alert alert-success" role="alert">
        <h2>Your comment has been added</h2>
        <p><a href="{{ post.get_absolute_url }}">Back to the post</a></p>
      </div>
      {% else %}
      <h2>Add a comment</h2>
      {% include "forumsite/post/includes/comment_form.html" %}
      {% endif %}
    </div>
  </div>
</div>

{% endblock content %}

forumsite/templates/forumsite/post/detail.html
{% extends 'forumsite/base.html' %}

{% load forumsite_tags %}


{% block title %} {{ post.title }} {% endblock title %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <h1>{{ post.title }}</h1>
      <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
      <div class="mb-4">
        {{ post.body | markdown }}
      </div>
      <p>
        <a href="{% url 'forum:post_share' post.id %}" class="btn btn-primary">Share this post</a>
      </p>

      <h2>Similar posts</h2>
      
      {% for post in similar_posts  %}
      <p><a href="{{post.get_absolute_url}}">{{post.title}}</a></p>
        {% empty %}
        There are no similar posts yet.
      {% endfor %}
        

      <h2>{{ comments.count }} comment{{ comments.count|pluralize }}</h2>
      {% for comment in comments %}
      <div class="card mb-3">
        <div class="card-body">
          <h5 class="card-title">Comment {{ forloop.counter }} by {{ comment.name }} {{ comment.created }}</h5>
          <p class="card-text">{{ comment.body | linebreaks }}</p>
        </div>
      </div>
      {% empty %}
      <p>There are no comments</p>
      {% endfor %}
      {% include "forumsite/post/includes/comment_form.html" %}
    </div>
  </div>
</div>
{% endblock %}

forumsite/templates/forumsite/post/includes/comment_form.html
{% comment %} <h2>Add a new comment</h2>
<form action="{% url 'forum:post_comment' post.id %}" method='post'>
{{form.as_p}}
{% csrf_token %}
<p><input type="submit" value="Add comment"></p>

</form> {% endcomment %}

<div class="container">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <h2>Add a new comment</h2>
        <form action="{% url 'forum:post_comment' post.id %}" method="post" class="mb-4">
          {% csrf_token %}
          <div class="mb-3">
            <label for="id_name" class="form-label">Your Name</label>
            {{ form.name }}
          </div>
          <div class="mb-3">
            <label for="id_email" class="form-label">Your Email</label>
            {{ form.email }}
          </div>
          <div class="mb-3">
            <label for="id_body" class="form-label">Comment</label>
            {{ form.body }}
          </div>
          <button type="submit" class="btn btn-primary">Add Comment</button>
        </form>
      </div>
    </div>
  </div>
  

forumsite/templates/forumsite/post/latest_posts.html
<ul>

    
    {% for post in latest_posts %}
        <li>

            <a href="{{post.get_absolute_url}}">{{post.title}}</a>
        </li>
    {% endfor %}
        
</ul>

forumsite/templates/forumsite/post/list.html
{% extends 'forumsite/base.html' %} 
{% load forumsite_tags %}

{% block title %} My Blog {% endblock title %} 

{% block content %} 
<div class="container">
  <div class="row">
    
    {% if tag %}
    <h2 class="mb-3 fs-3">Posts tagged with "{{tag.name}}"</h2>
      
    {% endif %}
      
    {% for post in posts %}
    <div class="col-md-4 mb-4">
      <div class="card h-100 border-0 shadow">
        <div class="card-body">
          <h5 class="card-title"><a href="{{ post.get_absolute_url }}" class="text-decoration-none">{{ post.title }}</a></h5>
          <p class="card-text">{{ post.body | markdown| truncatewords_html:30 }}</p>
          <p class="text-success fw-semibold">Tags:

            
            {% for tag in post.tags.all  %}
              <a href='{% url "forum:post_list_by_tag" tag.slug %}'>

                {{tag.name}}
              </a>
              
              {% if not forloop.last %}, {% endif %}
                
                
            {% endfor %}
              
          </p>
          <p class="card-text"><small class="text-muted">Published {{ post.publish }} by {{ post.author }}</small></p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% include "pagination.html" with page=posts %}
</div>

<style>
  .card:hover {
    transition: all 0.3s;
    transform: translateY(-5px);
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    cursor:pointer;
  }
</style>
{% endblock %}

forumsite/templates/forumsite/post/search.html
{% extends 'forumsite/base.html' %} 
{% load forumsite_tags %}
 {% block title %}
Search 
{% endblock title %} 
{% block content %} 
{% if query %}
<h2>Posts containing "{{query}}"</h2>
<h3>
  {% with results.count as total_results %} Found {{total_results}} result{{total_results|pluralize}} 
  {% endwith %}
</h3>

{% for post in results %}
<h4>
  <a href="{{post.get_absolute_url}}">{{post.title}}</a>
</h4>
{{post.body|markdown|truncatewords_html:10}} {% empty %}
<p>There are no results for your query</p>
{% endfor %}
<p><a href="{% url 'forumsite:post_search' %}">Search again</a></p>
{% else %}
<h2>Search for post</h2>
<form method="get">
    {{form.as_p}}
        <input type="submit" value="Search">
</form>
{% endif %} {% endblock content %}

forumsite/templates/forumsite/post/share.html
{% extends 'forumsite/base.html' %}

{% block title %}Share Post{% endblock title %}

{% block content %}

{% if sent %}

<h1>E-mail successfully sent</h1>
<p>"{{post.title}}" was successfully sent to {{form.cleaned_data.to}}</p>
  {% else %}
  <h1>Share "{{post.title}}" by e-mail</h1>
  <form action="" method="post">
{{form.as_p}}
{% csrf_token %}
<input type="submit" value="Send e-mail">

  </form>
{% endif %}
  
<a href="{% url 'forum:post_list' %}">Home</a>
{% endblock content %}

forumsite/templates/pagination.html
<div class="pagination">
    <span class="step-links">
      {% if page.has_previous %} 
  
      <a href="?page={{ page.previous_page_number }}">Previous</a>
      {% endif %}
  
      <span class="current">
        Page {{ page.number }} of {{ page.paginator.num_pages }}.
      </span>
      {% if page.has_next %} 
      <a href="?page={{ page.next_page_number }}">Next</a> 
      {% endif %}
    </span>
  </div>